import { kebabCase } from 'lodash-unified'

export const optimizeElement = [
  'Button',
  'Container',
  'Header',
  'Aside',
  'Main',
  'Footer',
  'Row',
  'Col',
  'Link',
  'Text',
  'Scrollbar',
  'Space',
  'Autocomplete',
  'Cascader',
  'CascaderPanel',
  'Checkbox',
  'CheckboxGroup',
  'CheckboxButton',
  'ColorPicker',
  'DatePicker',
  'Form',
  'FormItem',
  'Input',
  'InputNumber',
  'Radio',
  'RadioGroup',
  'RadioButton',
  'Rate',
  'Select',
  'Option',
  'OptionGroup',
  'Select-V2',
  'Slider',
  'Switch',
  'TimePicker',
  'TimeSelect',
  'Transfer',
  'Upload',
  'Avatar',
  'Badge',
  'Calendar',
  'Card',
  'Carousel',
  'CarouselItem',
  'Collapse',
  'CollapseItem',
  'Descriptions',
  'DescriptionsItem',
  'Empty',
  'Image',
  'infiniteScroll',
  // 'Pagination',
  'Progress',
  'Result',
  'Skeleton',
  'SkeletonItem',
  // 'Table',
  // 'TableColumn',
  // 'Table-V2',
  'Tag',
  'CheckTag',
  'Timeline',
  'TimelineItem',
  'Tree',
  'TreeSelect',
  'Tree-V2',
  'Statistic',
  'Countdown',
  'Affix',
  'Backtop',
  'Breadcrumb',
  'BreadcrumbItem',
  'Dropdown',
  'DropdownMenu',
  'DropdownItem',
  'Menu',
  'MenuItem',
  'SubMenu',
  'PageHeader',
  'Steps',
  'Step',
  'Tabs',
  'TabPane',
  'Alert',
  'Dialog',
  'Drawer',
  // 'Loading',
  // 'Message',
  // 'MessageBox',
  // 'Notification',
  'Popconfirm',
  'Popover',
  'Tooltip',
  'Divider'
].map(v => {
  const name = v.includes('-') ? v.toLowerCase() : kebabCase(v).toLowerCase()
  return `element-plus/es/components/${name}/style/css`
})
